name: safe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/appLogo.png
    - assets/google_icon.png
    - assets/Rice_spoilage_rate.png
    - assets/historical_trends.png